repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff # linter
        args: [--fix, --exit-non-zero-on-fix] # sort imports and fix
      - id: ruff-format # formatter

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: local
    hooks:
      - id: codeowners-validator
        name: CODEOWNERS validator
        language: docker_image
        pass_filenames: false
        entry: >
          -e REPOSITORY_PATH="."
          -e CHECKS="files,duppatterns,syntax"
          ghcr.io/mszostok/codeowners-validator:v0.7.4
